# Generated by Django 3.1.4 on 2021-01-20 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210115_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sale_price',
            new_name='discount',
        ),
    ]
