# Generated by Django 3.1.4 on 2021-01-20 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210120_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='alt_title',
        ),
    ]
